#SPDX-License-Identifier: MIT-0
---
- name: Create OAuth2 application in AAP
  import_tasks: oauth.yml
  tags: [create_oauth]

- name: Create AAP token
  import_tasks: create_token.yml
  tags: [create_token]

- name: Create OpenShift namespace
  import_tasks: namespace.yml
  tags: [create_namespace]

- name: Create OpenShift secrets
  import_tasks: oc_secrets.yml
  tags:
    - create_secrets
    - create_rhaap_secret
    - create_scm_secret

- name: Build plugin registry
  import_tasks: plugins.yml
  tags: [build_plugin]

- name: Deploy plugin registry app
  import_tasks: plugin_deploy.yml
  tags: [deploy_plugin]

- name: Generate Helm values with plugin integrity
  import_tasks: helm_values.yml
  tags:
    - helm
    - helm_plugins
    - generate_helm_values

- name: Update AAP OAuth2 application with RHAAP route
  import_tasks: update_aap_oauth.yml
  tags: [update_oauth]
