---
- name: Fail if client_secret is still encrypted placeholder
  fail:
    msg: "client_secret is encrypted and has not been replaced! Remove or overwrite the var."
  when: app_result.client_secret == "$encrypted$"

- name: "Create secret: secrets-rhaap-self-service-preview"
  redhat.openshift.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: secrets-rhaap-self-service-preview
        namespace: "{{ openshift_namespace }}"
      type: Opaque
      data:
        aap-host-url: "{{ controller_host | b64encode }}"
        aap-token: "{{ aap_token_result.ansible_facts.aap_token.token | b64encode }}"
        oauth-client-id: "{{ app_result.client_id | b64encode }}"
        oauth-client-secret: "{{ app_result.client_secret | b64encode }}"

- name: Normalize tokens
  set_fact:
    _gitlab_token: "{{ gitlab_token | default('', true) }}"
    _github_token: "{{ github_token | default('', true) }}"

- name: Build secrets-scm data
  set_fact:
    scm_secret_data: >-
      {{
        dict(
          [('gitlab-token', _gitlab_token)] if _gitlab_token != '' else []
          +
          [('github-token', _github_token)] if _github_token != '' else []
        )
      }}


- name: "Create secret: secrets-scm"
  redhat.openshift.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: secrets-scm
        namespace: "{{ openshift_namespace }}"
      type: Opaque
      stringData: "{{ scm_secret_data }}"

