- name: Get Route for RHAAP Helm release
  redhat.openshift.k8s:
    api_version: route.openshift.io/v1
    kind: Route
    name: rhaap-self-service-rhaap-self-service-preview
    namespace: "{{ namespace }}"
    state: present
  register: rhaap_route

- name: Set RHAAP route hostname fact
  set_fact:
    rhaap_route_hostname: "{{ rhaap_route.result.spec.host }}"

- name: Debug RHAAP route hostname
  debug:
    msg: "RHAAP route hostname: {{ rhaap_route_hostname }}"

- name: Set OAuth redirect URI and app URL
  set_fact:
    rhaap_redirect_url: "https://{{ rhaap_route_hostname }}/api/auth/rhaap/handler/frame"
    rhaap_app_url: "https://{{ rhaap_route_hostname }}"

- name: Update OAuth2 application in AAP with RHAAP route
  ansible.platform.application:
    name: "Self Service 1"
    description: "Self Service application"
    organization: "Default"
    state: present
    authorization_grant_type: authorization-code
    client_type: confidential
    redirect_uris:
      - "{{ rhaap_redirect_url }}"
    app_url: "{{ rhaap_app_url }}"
    aap_hostname: "{{ controller_host }}"
    aap_username: "{{ controller_username }}"
    aap_password: "{{ controller_password }}"
    aap_validate_certs: "{{ controller_verify_ssl }}"
  tags: [update_oauth]

