redhat-developer-hub:
  global:
    _environment:
      _development: false
      _production: true
    dynamic:
      plugins:
        - disabled: false
          package: ./dynamic-plugins/dist/backstage-community-plugin-rbac
        - disabled: false
          integrity: >-
            sha512-MMzJMaZH9/rxDsJD7At9t8ePkuxqoTanHQ+o1s8dnjhCgNx/kK+ioL164i7HH3yQ9bWjdPdNpZo6+Pa/jbE6SQ==
          package: >-
            http://plugin-registry:8080/ansible-plugin-scaffolder-backend-module-backstage-rhaap-dynamic-1.5.0.tgz
          pluginConfig:
            dynamicPlugins:
              backend:
                ansible.plugin-scaffolder-backend-module-backstage-rhaap: null
        - disabled: false
          integrity: >-
            sha512-Hxw9eOak6tiFXobrGRlC0KTu34MEaQJ+f5oUoao0bAbbheWmmu0tTq7ot+n9tItn4gxZEFyVn7FHW4op5Vm/dQ==
          package: >-
            http://plugin-registry:8080/ansible-backstage-plugin-catalog-backend-module-rhaap-dynamic-1.5.0.tgz
        - disabled: false
          integrity: >-
            sha512-x8nGhLtjMrjCgbeCFFYNOtQ8idRqA9A5cur6pKIpAjXInN3WI+iWI+vACttdPuPVsmYp5HBEmuIPOx79OUZrbw==
          package: >-
            http://plugin-registry:8080/ansible-plugin-backstage-self-service-dynamic-1.5.0.tgz
          pluginConfig:
            dynamicPlugins:
              frontend:
                ansible.plugin-backstage-self-service:
                  dynamicRoutes:
                    - importName: LandingPage
                      path: /
                    - importName: SelfServicePage
                      path: /self-service
                  mountPoints:
                    - importName: LocationListener
                      mountPoint: application/listener
                  providerSettings:
                    - description: Sign in with RHAAP
                      provider: ansible.auth.rhaap
                      title: RHAAP
                  scaffolderFieldExtensions:
                    - importName: AAPTokenFieldExtension
                    - importName: AAPResourcePickerExtension
                  signInPage:
                    importName: SignInPage
        - disabled: false
          integrity: >-
            sha512-H4L10ULACAP3EN+4P4HFbPAWx6NRnjFO92CFsJwcqAo/pQ5k0TWfvexAxFCZL1QzqOsZijhGT4uXZbFfxerBFA==
          package: >-
            http://plugin-registry:8080/ansible-backstage-plugin-auth-backend-module-rhaap-provider-dynamic-1.5.0.tgz
          pluginConfig: {}
        - disabled: false
          package: >-
            ./dynamic-plugins/dist/backstage-plugin-scaffolder-backend-module-github-dynamic
        - disabled: false
          package: >-
            ./dynamic-plugins/dist/backstage-plugin-scaffolder-backend-module-gitlab-dynamic
    imageTagInfo: main
  nameOverride: rhaap-self-service-preview
  test:
    enabled: false
  upstream:
    backstage:
      appConfig:
        ansible:
          creatorService:
            baseUrl: 127.0.0.1
            port: '8000'
          rhaap:
            baseUrl: '${AAP_HOST_URL}'
            schedule:
              frequency:
                seconds: 120
              timeout:
                seconds: 5
            showCaseLocation:
              target: /tmp/aap-showcases/
              type: file
            token: '${AAP_TOKEN}'
        app:
          branding:
            title: AAP Self-Service Technical Preview
        auth:
          environment: production
          providers:
            rhaap:
              production:
                clientId: '${OAUTH_CLIENT_ID}'
                clientSecret: '${OAUTH_CLIENT_SECRET}'
                host: '${AAP_HOST_URL}'
                signIn:
                  resolvers:
                    - resolver: usernameMatchingUser
          signInPage: rhaap
        catalog:
          import:
            entityFilename: catalog-info.yaml
            pullRequestBranchName: backstage-integration
          locations:
            - rules:
                - allow:
                    - Template
              target: >-
                https://github.com/ansible/ansible-rhdh-templates/blob/{{-
                include "templates.branch" . }}/seed.yaml
              type: url
            - rules:
                - allow:
                    - Template
              target: /tmp/aap-showcases/all.yaml
              type: file
          orphanStrategy: delete
          pollingInterval:
            seconds: 1
          processingInterval:
            seconds: 10
          providers:
            rhaap:
              '{{- include "catalog.providers.env" . }}':
                orgs: Default
                sync:
                  jobTemplates:
                    enabled: true
                    labels: []
                    schedule:
                      frequency:
                        minutes: 1
                      timeout:
                        seconds: 30
                  orgsUsersTeams:
                    schedule:
                      frequency:
                        minutes: 1
                      timeout:
                        seconds: 30
          rules:
            - allow:
                - Component
                - System
                - Group
                - Resource
                - Location
                - Template
                - API
                - Users
          stitchTimeout:
            minutes: 1
          stitchingStrategy:
            immediate: true
        dynamicPlugins:
          frontend:
            backstage.plugin-techdocs:
              dynamicRoutes:
                - importName: TechDocsIndexPage
                  path: /docs
                - importName: TechDocsReaderPage
                  path: '/docs/:namespace/:kind/:name/*'
            default.main-menu-items:
              menuItems:
                default.apis:
                  icon: extension
                  priority: 60
                  title: ''
                  to: api-docs
                default.catalog:
                  icon: category
                  priority: 80
                  title: ''
                  to: catalog
                default.create:
                  icon: add
                  priority: 40
                  title: ''
                  to: create
                default.home:
                  icon: home
                  priority: 100
                  title: ''
                  to: /
                default.learning-path:
                  icon: school
                  priority: 50
                  title: ''
                  to: learning-paths
                default.my-group:
                  icon: group
                  priority: 70
                  title: ''
                default.mycatalog:
                  icon: home
                  priority: 120
                  title: Templates
                  to: /self-service/catalog
                default.myitem:
                  icon: category
                  priority: 110
                  title: History
                  to: /self-service/create/tasks
            internal.plugin-dynamic-plugins-info:
              appIcons:
                - importName: PluginsInfoIcon
                  name: pluginsInfoIcon
                - importName: AdminIcon
                  name: adminIcon
              dynamicRoutes:
                - importName: DynamicPluginsInfoPage
                  path: /extensions
              menuItems:
                admin:
                  icon: adminIcon
                  title: Administration
                extensions:
                  icon: pluginsInfoIcon
                  parent: admin
                  title: ''
                  to: extensions
                licensing:
                  icon: pluginsInfoIcon
                  parent: admin
                  title: ''
                  to: licensing
                plugins:
                  icon: pluginsInfoIcon
                  parent: admin
                  title: ''
                  to: rbac
            red-hat-developer-hub.backstage-plugin-global-header:
              mountPoints:
                - config:
                    position: above-main-content
                  importName: GlobalHeader
                  mountPoint: application/header
                - config:
                    priority: 100
                  importName: SearchComponent
                  mountPoint: global.header/component
                - config:
                    priority: 99
                    props:
                      growFactor: 0
                  importName: Spacer
                  mountPoint: global.header/component
                - config:
                    priority: 90
                    props:
                      icon: add
                      title: Create...
                      to: /self-service/catalog
                  importName: HeaderIconButton
                  mountPoint: global.header/component
                - config:
                    priority: 50
                  importName: Divider
                  mountPoint: global.header/component
                - config:
                    priority: 10
                  importName: ProfileDropdown
                  mountPoint: global.header/component
                - config:
                    priority: 10
                  importName: LogoutButton
                  mountPoint: global.header/profile
        enableExperimentalRedirectFlow: true
        integrations:
          github:
            - host: github.com
              token: '${GITHUB_TOKEN}'
          gitlab:
            - host: gitlab.com
              token: '${GITLAB_TOKEN}'
        permission:
          enabled: true
          rbac:
            admin:
              superUsers:
                - name: 'user:default/admin'
              users:
                - name: 'user:default/admin'
            pluginsWithPermission:
              - catalog
              - scaffolder
              - permission
      extraContainers:
        - command:
            - adt
            - server
          image: '{{- include "deployment.container-image" . }}'
          imagePullPolicy: IfNotPresent
          name: ansible-devtools-server
          ports:
            - containerPort: 8000
      extraEnvVars:
        - name: BACKEND_SECRET
          valueFrom:
            secretKeyRef:
              key: backend-secret
              name: '{{ include "janus-idp.backend-secret-name" $ }}'
        - name: POSTGRESQL_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              key: postgres-password
              name: '{{- include "janus-idp.postgresql.secretName" . }}'
        - name: ENABLE_AUTH_PROVIDER_MODULE_OVERRIDE
          value: 'true'
        - name: SEGMENT_WRITE_KEY
          value: uCMHvkR5n5q2v57LNXHwvTYlGV8lqFR9
        - name: AAP_HOST_URL
          valueFrom:
            secretKeyRef:
              key: aap-host-url
              name: secrets-rhaap-self-service-preview
        - name: OAUTH_CLIENT_ID
          valueFrom:
            secretKeyRef:
              key: oauth-client-id
              name: secrets-rhaap-self-service-preview
        - name: OAUTH_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              key: oauth-client-secret
              name: secrets-rhaap-self-service-preview
        - name: AAP_TOKEN
          valueFrom:
            secretKeyRef:
              key: aap-token
              name: secrets-rhaap-self-service-preview
        - name: GITHUB_TOKEN
          valueFrom:
            secretKeyRef:
              key: github-token
              name: secrets-scm
              optional: true
        - name: GITLAB_TOKEN
          valueFrom:
            secretKeyRef:
              key: gitlab-token
              name: secrets-scm
              optional: true
      image:
        registry: registry.redhat.io
        repository: rhdh/rhdh-hub-rhel9
        tag: 1.5.1
    nameOverride: rhaap-self-service-preview

